### ISSUE TITLE
Vital animations are missing

### ISSUE THREAD

**Issue by MrAntares** [MrAntares/Ragna.roBrowser#11]
Game-breaking animations are missing:

- Spiritball, coin, elemental balls, etc..
- Warp portal(skill)
- Warp portal(map)
- Ground effects that show path or other quest related things (yggdrasil dungeon, new world)
- Crimson marker

**Comment by MrAntares** [comment]
- Warp portal placeholder added in...
- Safety wall effect added in..
- Fire Pillar effect added in..
- Land Protector effect added in..
- Spiritball added in...
- Songs, Wall of fog, Gospel, Evil land effect placeholders (there is much left to do with these) are added in..

...a lot of commits and fixes, so it is troublesome to list all :)
But hey, things are happening! ;)

**Comment by kontownik** [comment]
Hey @MrAntares , good to know the work we did was not just a wasted time ^^ Feel free to invite me to any Ragnarok server you guys are making :)

@tehasdf FYI buddy hah

**Comment by MrAntares** [comment]
@kontownik It's an honor seeing you here :) If you wan't you can try our server on https://play.ragna.ro/ . We started it in 2007 and it has been running ever since without stopping. Unfortunately, it became almost empty a few years ago, because it was a small friend based server and eventually everyone moved on with their lives. Some old friends appear sometimes for old time's sake, and I use it to test my developments and sometimes hunt some mvps, but it is readily available for other players as well. Anyone can join! :)

The desktop client is 2012-04-10 version, so the server uses that packet version, but there are areas where the webclient is already ahead, like Rebellion class. My aim is to get rid of the desktop client entirely, because it was always a huge frustration to get the proper version, hex it and make it work and even then there were many bugs because of the hexing.

**Comment by MrAntares** [comment]
I forgot to mention, that of course if you feel the urge to waste some time with coding, then don't hesitate to fork this repo and add some things :D:D
Just don't forget to push back :P

**Comment by tehasdf** [comment]
oh man, you guys make me nostalgic! Hopefully I'll be able to find some time to check out robrowser once again!

**Comment by MrAntares** [comment]
@tehasdf  That would be awesome :)

**Comment by MrAntares** [comment]
I close this since many of these are fixed now. Will open separate issues for remainder if I encounter them.

**Comment by MrAntares** [comment]
@tehasdf @kontownik Btw if you would like to peek into our group and see how it's going feel free to join on discord: https://discord.gg/8JdHwM4Kqm
