### ISSUE TITLE
Guild position change missing

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/Ragna.roBrowser#116]
Pic client vs browser [https://cdn.discordapp.com/attachments/1016019020983574630/1024669482393817168/unknown.png](https://cdn.discordapp.com/attachments/1016019020983574630/1024669482393817168/unknown.png)

**Comment by MrAntares** [comment]
Fixed in https://github.com/MrAntares/Ragna.roBrowser/commit/f4507c9c452efe9027ff68956ed84d1b65cdb6cd
