### ISSUE TITLE
Token of Siegfried resurrection window.

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/Ragna.roBrowser#125]
**Missing feature**
Token of Siegfried is missing alternative death window when you have the item in your inventory.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/214579/201814596-5ce7a3ac-524e-40a2-9e85-04b4a48dc0a3.png)

**Client Versions**
 - When cash items were implemented so before 2008 I guess and up to this date 2022+
 

**Packets**
N/A

**Comment by MrAntares** [comment]
Fixed in https://github.com/MrAntares/Ragna.roBrowser/commit/bfa54b508a22e9fe346cee0940a34c8f593bd5b5
