### ISSUE TITLE
Hom/Merc/Pet/Elem

### ISSUE THREAD

**Issue by MrAntares** [MrAntares/Ragna.roBrowser#13]
Homunculus, Mercenary, Pet, Elementals and similar things are not implemented, and thus are unusable and could lead to loss of minion, due to unable to feed.

**Comment by MrAntares** [comment]
Needs:
- stat windows
- skill windows
- skill hotkey handling
- right click menu
- alt click instuctions
- read the AI LUA/LUBs from the data files, parse it and send the proper packet to the server based on the AI instuctions

*click* noice

**Comment by MrAntares** [comment]
Elementals are also 100% working, since their logic is based on the server aka server-side bot.

**Comment by MrAntares** [comment]
Homunculus & Mercenary is still at 0%
Added LUA parser in https://github.com/MrAntares/Ragna.roBrowser/commit/1cf31676c31a9919889feb1f74441c3998d16a35
Anyone feel free to use it :D

**Comment by issid** [comment]
began to make a homunculus. at least basic (follow like a pet, feed)

**Comment by issid** [comment]
it is possible to use a virtual machine to run lua http://daurnimator.github.io/lua.vm.js/repl.html

**Comment by issid** [comment]
- [x] stat windows
- [x] skill windows
- [ ] right click menu
- [ ] (partially implemented) skill hotkey handling
- [ ] (partially implemented) alt click instuctions
- [ ] (partially implemented) read the AI LUA/LUBs from the data files, parse it and send the proper packet to the server based on the AI instuctions

**Comment by issid** [comment]
left to finish:
1. working context menu (difficult)
2. display hp when homunculus moves out of view

**Comment by MrAntares** [comment]
Although not finished entirely, but the core feature is done. Awesome work!
