### ISSUE TITLE
Weapon "slash" effect is missing.

### ISSUE THREAD

**Issue by MrAntares** [MrAntares/Ragna.roBrowser#130]
**Missing feature**
When attacking there should be a "slash" sprite effect displayed that is different for every class & weapon & action.
**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/5745362/204152972-7d690c3b-9d14-4209-a44c-620c7e1180a8.png)

**Client Versions**
All

**Packets**
All

**Comment by mrunzo** [comment]
Oh I just mention this on the other post.

**Comment by MrAntares** [comment]
Implemented in https://github.com/MrAntares/Ragna.roBrowser/commit/b3f1a70b4f1c2466c112bd8d94306dcf6cd9917d
Kudos to @MrUnzO
