### ISSUE TITLE
ALT-M shortcuts

### ISSUE THREAD

**Issue by MrAntares** [MrAntares/Ragna.roBrowser#14]
ALT-M shortcuts window is missing

**Comment by FranciscoWallison** [comment]
![image](https://user-images.githubusercontent.com/19413241/148664027-65fcba77-f1c6-42cc-91a1-7b54155228b1.png)
I started the activity

**Comment by MrAntares** [comment]
Awesome work!
One minor issue tho:
![image](https://user-images.githubusercontent.com/5745362/149944014-400e4734-e984-4197-a83e-46f35f35a6a1.png)
It displays this message even though I have learned the skill and the emoticon IS displayed, when I press the shortcut.
Otherwise, it is working perfectly :)

**Comment by MrAntares** [comment]
It might be a spam filter thingie on the server side. First try it goes off properly, but if I press again too fast it sends a 'skill level not enough packet'. Strange, but I consider this mostly finished regardless of this stupid server behaviour.
![image](https://user-images.githubusercontent.com/5745362/149950074-086672fb-6222-4b39-8cb6-ec4cee43a054.png)

**Comment by MrAntares** [comment]
https://github.com/MrAntares/Ragna.roBrowser/commit/d171fd29ee56ab113a514b31a5417e6f5f6809f3

**Comment by MrAntares** [comment]
Ok, now fixed :)
Pressing alt while chatting sends a guild message and when in guild mode it sends a normal message, effectively inverting the selected target when using ALT+M shortcuts.
https://github.com/MrAntares/Ragna.roBrowser/commit/cd74130722ed3ba7b6ea2ff85ec3c79cb0bf2ecc
