### ISSUE TITLE
Can't rotate the camera sometime after switch back to the game.

### ISSUE THREAD

**Issue by MrUnzO** [MrAntares/Ragna.roBrowser#153]
**Describe the bug**
When players go to another page, tab, or window and come back to the game they can't rotate the camera.

**Packet/Client version**
all version

**Comment by MrAntares** [comment]
I never had this problem and I multitask all the time.

**Comment by MrAntares** [comment]
Isnt it related to shift getting stuck sometimes?

**Comment by MrUnzO** [comment]
can you try to alt+tab to switch to another window and come back directly by clicking on the screen to activate window? I think it causes the Alt keys press state stuck in that state after the window switch to another window.

**Comment by MrUnzO** [comment]
> Isnt it related to shift getting stuck sometimes?

on my case is Alt keys state stuck I think

**Comment by MrUnzO** [comment]
Maybe we can reset all key's states after the window got focus?

**Comment by MrUnzO** [comment]
> Maybe we can reset all key states after the window got focused?

and where to put the reset key state after the window got focused?

**Comment by MrAntares** [comment]
Yeah probably that is a good idea. We cant detect keyup if focus is moves to other application/window.

**Comment by MrUnzO** [comment]
> Yeah probably that is a good idea. We cant detect keyup if focus is moves to other application/window.

I don't know to put this? xD

**Comment by MrAntares** [comment]
Maybe attach a window.onfocus event to the main document in key handler.

**Comment by MrUnzO** [comment]
> 

I think it works! I will make PR for it.
