### ISSUE TITLE
Effect rendering does not continue to render after the monster has died.

### ISSUE THREAD

**Issue by MrUnzO** [MrAntares/Ragna.roBrowser#158]
**Describe the bug**
When players use skills like Firebolt that need to render to the end (lv. 10 should display 10 bolts.) but the monster has died before the effect finishes rendering, the effect does not continue to render anymore. 

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/6884575/210057602-0749db27-8f89-4d7f-98f8-5f392371c58f.png)

**Packet/Client version**
all version

**Additional context**
The issue may occur after effect refactoring.

**Comment by MrAntares** [comment]
Fixed in 
https://github.com/MrAntares/Ragna.roBrowser/commit/da886b03524e7d4fb016e96d62b735da3a1339fd
https://github.com/MrAntares/Ragna.roBrowser/commit/84f460c2a05445474e6e60a1ce1041c7ac7ece89
