### ISSUE TITLE
Forging/Brewing/Cooking/etc

### ISSUE THREAD

**Issue by MrAntares** [MrAntares/Ragna.roBrowser#18]
..is missing

**Comment by MrAntares** [comment]
Arrow crafting Implemented in:
eeb0a65dd48da60155c19896f0f1321bef03d217
1d000c089ef0ce6d3052360a9191383da9c9775e
22efc16c74b0eab14e216382d043438b1dbc936f

**Comment by MrAntares** [comment]
Weapon Refining Implemented in:
640ef324c7cf96512caa58eac58711a909d1dbdf
6f4999f5f9ac140f854221fcd3434efdbaf820df
14bdaa4fd55fd8fc3192495dcf08b4db180dacbf

**Comment by MrAntares** [comment]
- Todo: check other mechanics that use the basic forging UI if they work properly with the implemented UI (They should)
- Handle inventory change when adding elemental stones/star crumb/etc..
- Disable material slots when not possible to add anything, like in brewing
- Only allow to add proper materials like elemental stones/star crumb/etc and don't allow anything else (the server side doesn't allow it anyways, but it looks funny on the UI to add a sword to your sword... yo dawg)

**Comment by MrAntares** [comment]
Summary:
- Arrow crafting - OK
- Weapon forging - OK
- Potion making - OK
- Elemental converter - OK
- Create new poison - OK
- Create DP - OK
- Ancilla - OK
- Holy water - OK
- Auto spell - OK
- Reading spellbook - OK
- Weapon refine - OK
- Repair weapon - OK
- Poisoning weapon - OK

- Change material - Missing (PACKET_ZC_ITEMLISTWIN_OPEN)

- Cooking - Missing (PACKET_ZC_MAKINGITEM_LIST)
- Rune craft - Missing (PACKET_ZC_MAKINGITEM_LIST)
- Mix cooking - Missing (PACKET_ZC_MAKINGITEM_LIST)
- Create bomb - Missing (PACKET_ZC_MAKINGITEM_LIST)
- Special pharmacy - Missing (PACKET_ZC_MAKINGITEM_LIST)

- Vending - Not working
- Buying shop - ???

- Sense - Missing output
- Talkie box - Missing input
- Graffiti - Missing input

- Capture pet - Missing the whole UI part
- Flag graffiti - Heck, even the Granny3D flags are missing :D

**Comment by FranciscoWallison** [comment]
## Lacking

Rune craft - Missing (PACKET_ZC_MAKINGITEM_LIST)  package usage is (PACKET_ZC_MAKABLEITEMLIST)

Pharmacy - Missing (PACKET_ZC_MAKABLEITEMLIST) 

## The ones that are done

Cooking - Missing (PACKET_ZC_MAKINGITEM_LIST) - OK

Mix cooking - (PACKET_ZC_MAKINGITEM_LIST) - OK
![image](https://user-images.githubusercontent.com/19413241/158248473-63dee80d-fe67-437f-a293-e401945e7e5c.png)

Create bomb - (PACKET_ZC_MAKINGITEM_LIST) - OK
![image](https://user-images.githubusercontent.com/19413241/158249464-67001d4d-3074-42e8-8d70-fd223cd7c576.png)

Special pharmacy - (PACKET_ZC_MAKINGITEM_LIST) - OK
![image](https://user-images.githubusercontent.com/19413241/158252238-57b0a468-93c1-48cd-9d68-66ac1a0141ed.png)

**Comment by FranciscoWallison** [comment]
> * Todo: verifique outras mecânicas que usam a interface do usuário de forjamento básico se elas funcionam corretamente com a interface do usuário implementada (devem)
> * _Lidar com a mudança de inventário ao adicionar pedras elementares/migalhas de estrela/etc. _ **-DONE**
> * Desative os slots de material quando não for possível adicionar nada, como na fabricação de cerveja
> * _Permita apenas adicionar materiais adequados como pedras elementares/migalhas de estrela/etc e não permita mais nada (o lado do servidor não permite de qualquer maneira, mas parece engraçado na interface do usuário adicionar uma espada à sua espada ... yo dawg) _ **-CONCLUÍDO**

I created this code to be able to see the items that can be produced, for the PACKET_ZC_MAKABLEITEMLIST
It's a bug in the layout, where does the information of the necessary items come from?

![image](https://user-images.githubusercontent.com/19413241/158290653-4da65596-3722-4c34-b264-8cbe34fdb6b3.png)

Example using red potion, of the Pharmacy skill
result:

![image](https://user-images.githubusercontent.com/19413241/158291026-28ec6b11-a215-4e07-b5a9-87e6da5fc409.png)

**Comment by MrAntares** [comment]
> 

The ingredient information does not come with packets from what I can tell. Probably there is an internal table, hardcoded in the client side. I checked the packet creation on the rA side as well and as you can see, the variables are there, but they are constant zeroes. It would be easy to fix if the server would send the list, but it seems that officially the client handles that part.

**Comment by FranciscoWallison** [comment]
> > 
> 
> The ingredient information does not come with packets from what I can tell. Probably there is an internal table, hardcoded in the client side. I checked the packet creation on the rA side as well and as you can see, the variables are there, but they are constant zeroes. It would be easy to fix if the server would send the list, but it seems that officially the client handles that part.

I found the file that controls the items
```metalprocessitemlist.txt```

![image](https://user-images.githubusercontent.com/19413241/158376717-ba063fb5-b3b3-4988-a871-20818f3dec63.png)

**Comment by MrAntares** [comment]
Awesome :)

**Comment by MrAntares** [comment]
Just tested everything. All is good except Pharmacy and Forging. The advance screen where you can put additional material got removed that I already implemented. I will fix this now if I can.

**Comment by MrAntares** [comment]
Fixed it in https://github.com/MrAntares/Ragna.roBrowser/commit/9a0549b1c34cc69241c163f005fd4954e1699611

**Comment by MrAntares** [comment]
Updated Summary:
- Arrow crafting - OK
- Weapon forging - OK
- Potion making - OK
- Elemental converter - OK
- Create new poison - OK
- Create DP - OK
- Ancilla - OK
- Holy water - OK
- Auto spell - OK
- Reading spellbook - OK
- Weapon refine - OK
- Repair weapon - OK
- Poisoning weapon - OK
- Cooking - OK
- Rune craft - OK
- Mix cooking - OK
- Create bomb - OK
- Special pharmacy - OK

- Vending - OK
- Capture pet - OK

- Change material - OK

- Buying shop - Missing (PACKET_ZC_OPEN_BUYING_STORE). A copy of vending with different packets.

- Sense - Missing output (PACKET_ZC_MONSTER_INFO)

- Talkie box - Missing input. Trap entities are not implemented.
- Graffiti - Missing input, output is SPR based ground effect, must implement it.

**Comment by MrAntares** [comment]
Since most of these are implemented, I close this issue and open separate ones for the remaining.
