### ISSUE TITLE
Packet "0xac4" not register

### ISSUE THREAD

**Issue by Antex** [MrAntares/Ragna.roBrowser#21]
Trying to connect to fresh rAthena and i've got an error

> Packet "0xac4" not register

most likely it happened because I have a packet version more than 20170315

rAthena's loginclif.cpp:

```
#if PACKETVER < 20170315
	int cmd = 0x69; // AC_ACCEPT_LOGIN
	int header = 47;
	int size = 32;
#else
	int cmd = 0xac4; // AC_ACCEPT_LOGIN3
	int header = 64;
	int size = 160;
#endif

```

something has changed in the authentication algorithm

**Comment by chilamkatana** [comment]
r u fix this error?
