### ISSUE TITLE
Overload resolution failed

### ISSUE THREAD

**Issue by waken22** [MrAntares/Ragna.roBrowser#63]
### Description
This bugs makes robrowser's screen black, and it starts to spam this error message when tries to render :
https://i.gyazo.com/ef8157768f2276d4fc71d20f63817c4f.mp4

### How to reproduce
To reproduce the bug i only need to scroll down/up quickly and it starts to happen.

**Comment by MrAntares** [comment]
I don't get this error. Which map are you on? When this happens? Does this happen on an unmodified source?

**Comment by waken22** [comment]
All maps i guess.
It happens when i move quickly the camera.
Yes, this happened me when i just configured the robrowser and run it.
I have double monitor, and 4k. No idea if this helps, it's weird honestly...

**Comment by MrAntares** [comment]
Now I get it. Similar thing happened to me when zoomed too quickly with touch screen while the browser also started zooming the content. No idea why this happens but I will try to debug it

**Comment by waken22** [comment]
I think it gonna be worth it to take the effort to fix this, since this happens so often.
At least to me, that i have the mania to scroll down/up.
